### ISSUE TITLE
Invalid JWT returned by `getTokenSilently()`

### ISSUE THREAD

**Issue by eemanioui** [auth0-training/labs-node-working-with-apis-spa#6]
Hi Team,

At `Step #8 of 8 (2: Working with APIs in Single Page Applications (SPA))` the app doesn't work as demonstrated in the screenshots. Specifically the following step: 
![image](https://github.com/auth0-training/labs-node-working-with-apis-spa/assets/64502428/f90ba3bb-c000-40f9-871f-d7b33d379b4a)
When I click on the `expenses` link in the navigation component, nothing happens, after further investigation and checking the network the tab, I see this 
![image](https://github.com/auth0-training/labs-node-working-with-apis-spa/assets/64502428/b44d5391-8681-4535-b260-ccb8708fc065)
![image](https://github.com/auth0-training/labs-node-working-with-apis-spa/assets/64502428/753a161d-4021-49bf-a60d-cf2641adb1fa)
I took the JWT (access token) returned by `auth0.getTokenSilently()` which is sent as part of the the request `Authorization` header and put it into the `jwt.io` to see its content, only to find out that the JWT body is empty and the JWT itself is invalid 
![image](https://github.com/auth0-training/labs-node-working-with-apis-spa/assets/64502428/63d06752-6530-418c-9515-237592ff3d1c).

I don't know what's going on but I think the value returned by the following line(in the `expensesApi.js` module):
```js
const token = await window.auth0Client.getTokenSilently();
``` 
is not a valid Access Token, but I could be wrong.

**Comment by kazemicode** [comment]
Thanks for the catch! Looks like an update to an SDK broke this. There's a slight change in how you pass the audience and scopes param. Because of this, they weren't getting passed properly and we were getting back an opaque access token.
